### ISSUE TITLE
Function definitions should be in different files

### ISSUE THREAD

**Issue by okovtun** [TipsyLady/Functions#4]
Здравствуйте Маша! А почему *.cpp-файлики пустые?)

**Comment by TipsyLady** [comment]
Oleg, when I am trying to put function defenition in *.cpp files , in computing the error "LNK2019	unresolved external symbol "void __cdecl Print<char>(char * const,int)" (??$Print@D@@YAXQADH@Z) referenced in function _main	Functions	" appears. How to solve this bug? I only put non-templated functions defenitions in *.cpp files.(Fillrand and Unicrand)

**Comment by TipsyLady** [comment]
The task was done
